name: FusionRep
version: '1.0'
main: org.fusion.fusionRep.FusionRep
api-version: '1.21'
commands:
  myreputation:
    aliases:
      - myrep
    description: Show your reputation
    usage: /myreputation
